#!/usr/bin/env python3
"""Build chapters 2+ from OCR text.

This is a pragmatic bulk builder: Chapter 1 remains the curated hand-edited
preview generated by build_ch01_from_pdf.py. Remaining chapters are generated
from OCR text as AI-draft study cards, using stable IDs and filenames:

  chapter_id: ch_02
  section_id: sec_01
  point_id: 001
  file: ch_02_sec_01_001.json / .md
"""

from __future__ import annotations

import importlib.util
import json
import re
import shutil
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONTENT_ROOT = ROOT / "content_package"
SUBJECT_ID = "high_itpmp"
BUILD_TIME = "2026-05-11T00:00:00+08:00"
SOURCE_ID = "pdf_2026_tricolor_high"
DEFAULT_OCR_TEXT = Path("/private/tmp/atomq_all_ocr.txt")


def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.strip() + "\n", encoding="utf-8")


def run_ch01_builder() -> None:
    script = ROOT / "scripts" / "build_ch01_from_pdf.py"
    spec = importlib.util.spec_from_file_location("build_ch01_from_pdf", script)
    module = importlib.util.module_from_spec(spec)
    sys.modules["build_ch01_from_pdf"] = module
    assert spec.loader is not None
    spec.loader.exec_module(module)
    module.build()


def normalize_text(text: str) -> str:
    replacements = {
        "咸⻥": "咸鱼",
        "千": "于",
        "—": "-",
        "－": "-",
        "“": "\"",
        "”": "\"",
        "＂": "\"",
        "（": "(",
        "）": ")",
        "，": "，",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    lines = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("==="):
            continue
        if "更多资料请" in line or line == "环球课堂":
            continue
        if any(token in line for token in ["本章分值预测", "预计选择题", "论文写作", "不需要人真学", "随缘", "需要把教材原文"]):
            continue
        if re.fullmatch(r"第?\d+\s*页", line):
            continue
        lines.append(line)
    return "\n".join(lines)


CHAPTER_RE = re.compile(r"第\s*(\d{1,2})\s*章\s*[-—－]\s*([^\n]+)")


def split_chapters(text: str) -> list[dict[str, object]]:
    matches = list(CHAPTER_RE.finditer(text))
    chapters = []
    for idx, match in enumerate(matches):
        number = int(match.group(1))
        title = match.group(2).strip()
        start = match.end()
        end = matches[idx + 1].start() if idx + 1 < len(matches) else len(text)
        body = text[start:end].strip()
        chapters.append({"number": number, "title": title, "body": body})
    return chapters


SECTION_PATTERNS = [
    re.compile(r"^(\d{1,2})\.\s*(\d{1,2})\s*(.{2,40})$"),
    re.compile(r"^【([一二三四五六七八九十]+)、(.{2,40})】$"),
    re.compile(r"^([一二三四五六七八九十]+)、(.{2,40})$"),
]


def section_heading(line: str) -> str | None:
    if "本章分值预测" in line:
        return "章节导读"
    for pattern in SECTION_PATTERNS:
        match = pattern.match(line)
        if not match:
            continue
        title = match.group(match.lastindex or 1).strip()
        title = re.sub(r"\s+", "", title)
        title = title[:24]
        if len(title) >= 2:
            return title
    return None


def split_sections(chapter_body: str) -> list[dict[str, object]]:
    lines = chapter_body.splitlines()
    sections: list[dict[str, object]] = []
    current_title = "章节核心考点"
    current_lines: list[str] = []

    def flush() -> None:
        nonlocal current_lines, current_title
        text = "\n".join(current_lines).strip()
        if text:
            sections.append({"title": current_title, "text": text})
        current_lines = []

    for line in lines:
        heading = section_heading(line)
        if heading and current_lines:
            flush()
            current_title = heading
        elif heading and not current_lines:
            current_title = heading
        else:
            current_lines.append(line)
    flush()

    if not sections and chapter_body.strip():
        sections.append({"title": "章节核心考点", "text": chapter_body.strip()})

    # Merge tiny leading section into next one.
    if len(sections) > 1 and len(str(sections[0]["text"])) < 180:
        sections[1]["text"] = f"{sections[0]['text']}\n{sections[1]['text']}"
        sections = sections[1:]

    return sections


def clean_title(text: str, fallback: str) -> str:
    skip_tokens = ["容比较简单", "本章学", "理解记忆", "把握关键词", "案例和论文", "论文应该"]
    first = fallback
    for candidate in text.splitlines():
        if any(token in candidate for token in skip_tokens):
            continue
        if len(candidate.strip()) >= 3:
            first = candidate
            break
    first = re.sub(r"^[0-9一二三四五六七八九十]+[、.．]\s*", "", first)
    first = re.sub(r"[：:，,。；;].*$", "", first)
    first = re.sub(r"[^\w\u4e00-\u9fff（）()A-Za-z0-9/+-]+", "", first)
    return (first or fallback)[:22]


def split_cards(section_text: str) -> list[str]:
    lines = section_text.splitlines()
    chunks: list[list[str]] = []
    current: list[str] = []
    item_re = re.compile(r"^(\d{1,2}|[一二三四五六七八九十]+)[、.．]\s*")

    for line in lines:
        starts_new = bool(item_re.match(line)) and len("\n".join(current)) > 260
        if starts_new:
            chunks.append(current)
            current = [line]
        else:
            current.append(line)
            if len("\n".join(current)) > 950:
                chunks.append(current)
                current = []
    if current:
        chunks.append(current)

    result = []
    for chunk in chunks:
        text = "\n".join(chunk).strip()
        if len(text) < 80 and result:
            result[-1] = f"{result[-1]}\n{text}"
        elif text:
            result.append(text)
    return result


def make_key_points(text: str) -> str:
    lines = [line.strip("•◆> ") for line in text.splitlines() if line.strip()]
    candidates = []
    for line in lines:
        if any(mark in line for mark in ["是", "包括", "分为", "主要", "必须", "核心", "作用", "输出", "输入"]):
            candidates.append(line)
        if len(candidates) >= 3:
            break
    if not candidates:
        candidates = lines[:2]
    return "\n".join(f"{idx + 1}. {candidate[:80]}" for idx, candidate in enumerate(candidates))


def make_markdown(title: str, raw: str) -> str:
    lines = [line for line in raw.splitlines() if line.strip()]
    overview = lines[0] if lines else title
    bullets = lines[1:8]
    bullet_text = "\n".join(f"- {line}" for line in bullets)
    key_points = make_key_points(raw)
    body = f"""### 概述

=={title}== 是本章需要掌握的考点之一。{overview}

### 结构化要点

{bullet_text if bullet_text else '- 该考点来自原始 PDF 的 OCR 识别结果，需人工复核后发布。'}

:::key
{key_points}
:::

:::warning
本卡片由 OCR 文本自动整理，`review_status` 为 `ai_draft`，上线前需要人工核对原文、表格和红色重点。
:::
"""
    return body


def infer_card_type(title: str, text: str) -> str:
    if "过程" in title or "流程" in title or "管理" in title:
        return "process"
    if "区别" in title or "对比" in title or "比较" in title:
        return "comparison"
    if "公式" in title or "计算" in title:
        return "formula"
    if "定义" in text[:80]:
        return "definition"
    return "concept"


def infer_difficulty(text: str) -> int:
    if len(text) > 850 or any(token in text for token in ["计算", "公式", "挣值", "案例", "论文"]):
        return 3
    if len(text) > 420 or any(token in text for token in ["过程", "输入", "输出", "工具", "技术"]):
        return 2
    return 1


def tags_for(title: str, section_title: str, chapter_title: str) -> list[str]:
    tags = [chapter_title, section_title, title]
    clean = []
    for tag in tags:
        tag = re.sub(r"^[0-9一二三四五六七八九十、.．\s]+", "", tag).strip()
        if tag and tag not in clean:
            clean.append(tag[:16])
    return clean[:5]


def build_chapter(chapter: dict[str, object]) -> dict[str, object]:
    number = int(chapter["number"])
    chapter_id = f"ch_{number:02d}"
    chapter_title = str(chapter["title"]).strip()
    body = normalize_text(str(chapter["body"]))
    sections = split_sections(body)

    chapter_dir = CONTENT_ROOT / "subjects" / SUBJECT_ID / "chapters" / chapter_id
    cards_dir = chapter_dir / "cards"
    cards_dir.mkdir(parents=True, exist_ok=True)

    section_meta = []
    card_count = 0
    previous_point_id: str | None = None
    for section_index, section in enumerate(sections, start=1):
        section_id = f"sec_{section_index:02d}"
        section_title = str(section["title"])
        chunks = split_cards(str(section["text"]))
        section_card_count = 0
        for chunk in chunks:
            card_count += 1
            section_card_count += 1
            point_id = f"{card_count:03d}"
            title = clean_title(chunk, section_title)
            stem = f"{chapter_id}_{section_id}_{point_id}"
            related_prev = [previous_point_id] if previous_point_id else []
            meta = {
                "point_id": point_id,
                "subject_id": SUBJECT_ID,
                "chapter_id": chapter_id,
                "section_id": section_id,
                "title": title,
                "card_type": infer_card_type(title, chunk),
                "difficulty": infer_difficulty(chunk),
                "estimated_read_seconds": min(300, max(60, int(len(chunk) / 3.2))),
                "has_key_content": True,
                "is_free": card_count <= 3,
                "sort_no": card_count,
                "content_file": f"{stem}.md",
                "tags": tags_for(title, section_title, chapter_title),
                "key_points": make_key_points(chunk),
                "mnemonics": "",
                "prerequisite_point_ids": related_prev,
                "related_point_ids": [],
                "related_question_ids": [],
                "source": "2026新版高项三色笔记（信息系统项目管理师）",
                "source_type": "exam_note",
                "source_refs": [{"source_id": SOURCE_ID, "page_label": "OCR自动定位待复核"}],
                "author": "Codex OCR 批量整理",
                "reviewer": "待人工复核",
                "review_status": "ai_draft",
                "created_at": BUILD_TIME,
                "updated_at": BUILD_TIME,
                "version": 1,
                "schema_version": 2,
            }
            write_json(cards_dir / f"{stem}.json", meta)
            write_text(cards_dir / f"{stem}.md", make_markdown(title, chunk))
            previous_point_id = point_id

        section_meta.append(
            {
                "section_id": section_id,
                "title": section_title,
                "sort_no": section_index,
                "description": f"{chapter_title} - {section_title}",
                "card_count": section_card_count,
            }
        )

    chapter_meta = {
        "chapter_id": chapter_id,
        "subject_id": SUBJECT_ID,
        "title": chapter_title,
        "description": f"{chapter_title}，由 PDF OCR 文本自动整理为知识卡片草稿。",
        "sort_no": number,
        "sections": section_meta,
        "schema_version": 2,
    }
    write_json(chapter_dir / "chapter_meta.json", chapter_meta)
    return {"chapter_id": chapter_id, "title": chapter_title, "sort_no": number, "card_count": card_count, "question_count": 0}


def rebuild_subject_index(extra_chapters: list[dict[str, object]]) -> None:
    subject_path = CONTENT_ROOT / "subjects" / SUBJECT_ID / "subject_index.json"
    subject = load_json(subject_path)
    existing = [chapter for chapter in subject["chapters"] if chapter["chapter_id"] == "ch_01"]
    chapters = sorted(existing + extra_chapters, key=lambda item: item["sort_no"])
    subject["chapters"] = chapters
    write_json(subject_path, subject)

    manifest_path = CONTENT_ROOT / "manifest.json"
    manifest = load_json(manifest_path)
    manifest["package_id"] = "atomq_high_itpmp_2026_full_ocr_draft"
    manifest["content_version"] = "2026.05.full-ocr-draft.1"
    manifest["chapters"] = [
        {"chapter_id": item["chapter_id"], "title": item["title"], "card_count": item["card_count"], "question_count": item["question_count"]}
        for item in chapters
    ]
    write_json(manifest_path, manifest)


def main() -> int:
    ocr_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_OCR_TEXT
    if not ocr_path.exists():
        print(f"Missing OCR text: {ocr_path}", file=sys.stderr)
        return 2

    run_ch01_builder()
    text = normalize_text(ocr_path.read_text(encoding="utf-8"))
    chapters = split_chapters(text)
    extra = []
    for chapter in chapters:
        number = int(chapter["number"])
        if number <= 1:
            continue
        extra.append(build_chapter(chapter))
    rebuild_subject_index(extra)

    source_manifest_path = ROOT / "sources" / "source_manifest.json"
    source_manifest = load_json(source_manifest_path)
    source_manifest["ocr_text_path_used_for_bulk_build"] = str(ocr_path)
    source_manifest["generated_chapters"] = [item["chapter_id"] for item in extra]
    source_manifest["notes"].append("Chapters 2+ were generated from macOS Vision OCR output as ai_draft cards.")
    write_json(source_manifest_path, source_manifest)

    print(f"Generated {len(extra)} additional chapters.")
    print(f"Generated {sum(item['card_count'] for item in extra)} additional cards.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
