#!/usr/bin/env python3
"""Rebuild chapter 1 cards from color-aware OCR output.

The color-aware OCR JSON is generated by data/scripts/ocr_pdf_with_color.swift.
Red OCR lines are preserved in Markdown as ==highlight==, while JSON key_points
remain curated summaries rather than a direct dump of red text.
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PUBLIC_ROOT = ROOT / "content_package" / "public"
SUBJECT_ROOT = PUBLIC_ROOT / "subjects" / "high_itpmp"
CHAPTER_ROOT = SUBJECT_ROOT / "chapters" / "ch_01"
CARDS_DIR = CHAPTER_ROOT / "cards"
OCR_JSON = Path("/private/tmp/ch01_color_ocr.json")


CHAPTER_ID = "ch_01"
SUBJECT_ID = "high_itpmp"


def normalize(text: str) -> str:
    return re.sub(r"\s+", "", text.strip())


def display_text(text: str) -> str:
    text = re.sub(r"\s+", " ", text.strip())
    return text.replace("==", "")


def should_skip(text: str) -> bool:
    compact = normalize(text)
    if not compact:
        return True
    if compact.startswith("更多资料请") or compact.startswith("第") and compact.endswith("页"):
        return True
    if "环球课堂" in compact or "非机构资料" in compact:
        return True
    if compact.startswith("2026"):
        return True
    if compact in {"1.1信息与信息化", "1.2现代化基础设施", "1.3现代化创新发展", "1.4数字中国", "1.5数字化转型与元宇宙"}:
        return True
    if compact.startswith("本章（第1章）标题类知识点总结"):
        return True
    return False


def line_to_markdown(record: dict) -> str | None:
    text = display_text(record["text"])
    if should_skip(text):
        return None
    if record.get("color") == "red":
        return f"- =={text}=="
    return f"- {text}"


def find_index(records: list[dict], pattern: str, start: int = 0) -> int:
    rx = re.compile(pattern)
    for index in range(start, len(records)):
        if rx.search(normalize(records[index]["text"])):
            return index
    raise ValueError(f"Pattern not found: {pattern}")


def slice_until_page(records: list[dict], start: int, end_page_exclusive: int) -> int:
    for index in range(start, len(records)):
        if records[index]["page"] >= end_page_exclusive:
            return index
    return len(records)


def split_cards(records: list[dict], start_patterns: list[str], section_end: int) -> list[list[dict]]:
    starts: list[int] = []
    cursor = 0
    for pattern in start_patterns:
        index = find_index(records, pattern, cursor)
        if index >= section_end:
            raise ValueError(f"Pattern {pattern} is outside section range")
        starts.append(index)
        cursor = index + 1

    blocks: list[list[dict]] = []
    for pos, start in enumerate(starts):
        end = starts[pos + 1] if pos + 1 < len(starts) else section_end
        blocks.append(records[start:end])
    return blocks


def first_highlight(block: list[dict]) -> str:
    for record in block:
        if record.get("color") == "red" and not should_skip(record["text"]):
            return display_text(record["text"]).lstrip("0123456789、. ")
    for record in block:
        if not should_skip(record["text"]):
            return display_text(record["text"]).lstrip("0123456789、. ")
    return ""


def make_card(point_no: int, section_id: str, title: str, block: list[dict], sort_no: int) -> tuple[dict, str]:
    point_id = f"{point_no:03d}"
    filename_base = f"{CHAPTER_ID}_{section_id}_{point_id}"
    source_pages = sorted({record["page"] for record in block})
    md_lines = [line_to_markdown(record) for record in block]
    md_lines = [line for line in md_lines if line]
    has_highlight = any("==" in line for line in md_lines)

    summary = first_highlight(block)
    key_points = [summary] if summary else [title]
    if summary and title not in summary:
        key_points.insert(0, title)

    md = "\n".join(
        [
            f"# {title}",
            "",
            "## 原文要点",
            "",
            *md_lines,
            "",
            "## 记忆抓手",
            "",
            f"- {key_points[0]}",
            "",
        ]
    )

    meta = {
        "point_id": point_id,
        "subject_id": SUBJECT_ID,
        "chapter_id": CHAPTER_ID,
        "section_id": section_id,
        "title": title,
        "card_type": "concept",
        "difficulty": 2,
        "estimated_read_seconds": max(60, min(240, len(md_lines) * 8)),
        "has_key_content": has_highlight,
        "is_free": True,
        "sort_no": sort_no,
        "tags": ["信息化发展"],
        "key_points": key_points[:3],
        "mnemonics": [],
        "common_mistakes": [],
        "review_status": "ai_draft",
        "content_file": f"{filename_base}.md",
        "content_md_path": f"subjects/{SUBJECT_ID}/chapters/{CHAPTER_ID}/cards/{filename_base}.md",
        "source_refs": [
            {
                "source": "2026新版高项三色笔记（信息系统项目管理师）",
                "location": f"拆分PDF 01 第{page}页",
            }
            for page in source_pages
        ],
    }
    return meta, md


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def build_file_index() -> None:
    entries = []
    for path in sorted(PUBLIC_ROOT.rglob("*")):
        if path.is_file() and path.name != "file_index.json":
            entries.append(
                {
                    "path": path.relative_to(PUBLIC_ROOT).as_posix(),
                    "bytes": path.stat().st_size,
                    "sha256": sha256(path),
                }
            )
    write_json(
        PUBLIC_ROOT / "file_index.json",
        {
            "package_id": "atomq_public_content",
            "version": "2026.1.0",
            "file_count": len(entries),
            "files": entries,
        },
    )


def main() -> None:
    if not OCR_JSON.exists():
        raise SystemExit(f"Missing OCR JSON: {OCR_JSON}")

    records = json.loads(OCR_JSON.read_text(encoding="utf-8"))
    records = sorted(records, key=lambda item: (item["page"], -item["y"], item["x"]))

    section_specs = [
        {
            "section_id": "sec_01",
            "title": "信息与信息化",
            "section_start": r"^1\.1信息与信息化$",
            "next_section": r"^1\.2现代化基础设施$",
            "card_titles": [
                "信息的定义",
                "维纳与香农的信息观点",
                "信息的特征",
                "信息质量属性",
                "信息系统定义与显著特点",
                "信息系统组成部件",
                "软件生命周期",
                "信息系统生命周期",
                "信息化核心",
                "信息化内涵",
                "国家信息化体系六要素",
                "组织信息化趋势",
                "国家信息化发展战略",
                "十四五国家信息化规划",
            ],
            "card_starts": [
                r"^1、信息是",
                r"^2、控制论",
                r"^3、信息的特征",
                r"^4、信息的质量属性",
                r"^5、信息系统",
                r"^6、信息系统的组成部件",
                r"^7、软件的生命周期",
                r"^8、信息系统的生命周期",
                r"^9、信息化的核心",
                r"^10、信息化内涵",
                r"^11、国家信息化体系",
                r"^信息化呈现出",
                r"^2016年8月",
                r"^《“十四五”国家信息化规划》",
            ],
        },
        {
            "section_id": "sec_02",
            "title": "现代化基础设施",
            "section_start": r"^1\.2现代化基础设施$",
            "next_section": r"^1\.3现代化创新发展$",
            "card_titles": ["新型基础设施建设", "工业互联网", "车联网"],
            "card_starts": [r"^1、新型基础设施建设", r"^2、工业互联网", r"^3、车联网"],
        },
        {
            "section_id": "sec_03",
            "title": "现代化创新发展",
            "section_start": r"^1\.3现代化创新发展$",
            "next_section": r"^1\.4数字中国$",
            "card_titles": ["农业现代化", "两化融合", "智能制造", "消费互联网"],
            "card_starts": [r"^1、农业现代化", r"^2、两化融合", r"^3、智能制造", r"^4、消费互联网"],
        },
        {
            "section_id": "sec_04",
            "title": "数字中国",
            "section_start": r"^1\.4数字中国$",
            "next_section": r"^1\.5数字化转型与元宇宙$",
            "card_titles": ["数字中国总体要求", "数字经济", "数字政府", "数字民生、智慧城市与数字乡村", "数字生态"],
            "card_starts": [
                r"^1、“迎接数字时代",
                r"^2、数字经济",
                r"^3、数字政府",
                r"^4、数字民生、智慧城市",
                r"^5、数字生态",
            ],
        },
        {
            "section_id": "sec_05",
            "title": "数字化转型与元宇宙",
            "section_start": r"^1\.5数字化转型与元宇宙$",
            "end_page_exclusive": 13,
            "card_titles": ["数字化转型", "元宇宙"],
            "card_starts": [r"^1、数字化转型", r"^2、元宇宙"],
        },
    ]

    if CARDS_DIR.exists():
        shutil.rmtree(CARDS_DIR)
    CARDS_DIR.mkdir(parents=True, exist_ok=True)

    point_no = 1
    sort_no = 1
    all_cards: list[dict] = []
    sections: list[dict] = []
    for spec in section_specs:
        section_start = find_index(records, spec["section_start"])
        if "next_section" in spec:
            section_end = find_index(records, spec["next_section"], section_start + 1)
        else:
            section_end = slice_until_page(records, section_start + 1, spec["end_page_exclusive"])
        blocks = split_cards(records[section_start:section_end], spec["card_starts"], section_end - section_start)
        if len(blocks) != len(spec["card_titles"]):
            raise ValueError(f"{spec['section_id']} card count mismatch")

        section_card_count = 0
        for title, block in zip(spec["card_titles"], blocks):
            meta, md = make_card(point_no, spec["section_id"], title, block, sort_no)
            base = f"{CHAPTER_ID}_{spec['section_id']}_{point_no:03d}"
            write_json(CARDS_DIR / f"{base}.json", meta)
            (CARDS_DIR / f"{base}.md").write_text(md, encoding="utf-8")
            all_cards.append(meta)
            point_no += 1
            sort_no += 1
            section_card_count += 1

        sections.append(
            {
                "section_id": spec["section_id"],
                "title": spec["title"],
                "sort_no": len(sections) + 1,
                "card_count": section_card_count,
            }
        )

    chapter_meta = {
        "chapter_id": CHAPTER_ID,
        "subject_id": SUBJECT_ID,
        "title": "信息化发展",
        "sort_no": 1,
        "is_free": True,
        "card_count": len(all_cards),
        "question_count": 7,
        "sections": sections,
    }
    write_json(CHAPTER_ROOT / "chapter_meta.json", chapter_meta)

    subject_index_path = SUBJECT_ROOT / "subject_index.json"
    subject_index = json.loads(subject_index_path.read_text(encoding="utf-8"))
    for chapter in subject_index["chapters"]:
        if chapter["chapter_id"] == CHAPTER_ID:
            chapter["card_count"] = len(all_cards)
            chapter["question_count"] = 7
            break
    write_json(subject_index_path, subject_index)

    manifest_path = PUBLIC_ROOT / "manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest_chapters = manifest.get("chapters", [])
    if "subjects" in manifest:
        for subject in manifest["subjects"]:
            if subject.get("subject_id") == SUBJECT_ID:
                manifest_chapters = subject.get("chapters", [])
                break
    for chapter in manifest_chapters:
        if chapter["chapter_id"] == CHAPTER_ID:
            chapter["card_count"] = len(all_cards)
            chapter["question_count"] = 7
            break
    write_json(manifest_path, manifest)
    build_file_index()

    print(f"Rebuilt {CHAPTER_ID}: {len(sections)} sections, {len(all_cards)} cards")
    for section in sections:
        print(f"- {section['section_id']} {section['title']}: {section['card_count']}")


if __name__ == "__main__":
    main()
